name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]  # Hanya trigger saat push ke branch main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:  # Tambahkan izin write untuk deployment
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Pastikan path benar (root folder)
          publish_branch: gh-pages  # Spesifikasikan branch tujuan